/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import controller.MainController;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;

/**
 *
 * @author MSI
 */
public class CourseManagement extends javax.swing.JFrame {

    /**
     * Creates new form CourseManagement
     */
    MainController control;
    
    public CourseManagement() {
        initComponents();
        control = new MainController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel();
        jLabel1 = new JLabel();
        btAdd = new JButton();
        btDisplay = new JButton();
        btSearch = new JButton();
        btExit = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Courses Management");

        btAdd.setFont(new Font("Tahoma", 0, 12)); // NOI18N
        btAdd.setText("Add a new Course");
        btAdd.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        btDisplay.setFont(new Font("Tahoma", 0, 12)); // NOI18N
        btDisplay.setText("Display all Courses");
        btDisplay.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btDisplayActionPerformed(evt);
            }
        });

        btSearch.setFont(new Font("Tahoma", 0, 12)); // NOI18N
        btSearch.setText("Search Course by Course Code");
        btSearch.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btSearchActionPerformed(evt);
            }
        });

        btExit.setFont(new Font("Tahoma", 0, 12)); // NOI18N
        btExit.setText("Exit Application");
        btExit.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(btDisplay, GroupLayout.PREFERRED_SIZE, 354, GroupLayout.PREFERRED_SIZE)
                            .addComponent(btAdd, GroupLayout.PREFERRED_SIZE, 354, GroupLayout.PREFERRED_SIZE)
                            .addComponent(btSearch, GroupLayout.PREFERRED_SIZE, 354, GroupLayout.PREFERRED_SIZE)
                            .addComponent(btExit, GroupLayout.PREFERRED_SIZE, 354, GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(btAdd)
                .addGap(28, 28, 28)
                .addComponent(btDisplay)
                .addGap(29, 29, 29)
                .addComponent(btSearch)
                .addGap(29, 29, 29)
                .addComponent(btExit)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btExitActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        control.btExit();
    }//GEN-LAST:event_btExitActionPerformed

    private void btAddActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        control.btAdd();
    }//GEN-LAST:event_btAddActionPerformed

    private void btDisplayActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btDisplayActionPerformed
        control.btDisplay();
    }//GEN-LAST:event_btDisplayActionPerformed

    private void btSearchActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btSearchActionPerformed
        control.btSearch();
    }//GEN-LAST:event_btSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CourseManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CourseManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CourseManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourseManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CourseManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btAdd;
    private JButton btDisplay;
    private JButton btExit;
    private JButton btSearch;
    private JLabel jLabel1;
    private JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
