
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSeparator;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;
import javax.swing.border.BevelBorder;
import javax.swing.border.LineBorder;
import javax.swing.border.SoftBevelBorder;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MSI
 */
public class CalculatorFrame extends javax.swing.JFrame {

    /**
     * Creates new form CalculatorFrame
     */
//    Controller control;
    Control control;
    
    public CalculatorFrame() {
        initComponents();
//        control = new Controller(this);
        control = new Control(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel();
        labelDisplay = new JLabel();
        labelClear = new JLabel();
        jSeparator1 = new JSeparator();
        jPanel2 = new JPanel();
        buttonMc = new JButton();
        button7 = new JButton();
        button4 = new JButton();
        button1 = new JButton();
        button0 = new JButton();
        buttonMr = new JButton();
        button8 = new JButton();
        button5 = new JButton();
        button2 = new JButton();
        buttonDot = new JButton();
        buttonMp = new JButton();
        button9 = new JButton();
        button6 = new JButton();
        button3 = new JButton();
        buttonOpposite = new JButton();
        buttonMm = new JButton();
        buttonSq = new JButton();
        buttonDiv = new JButton();
        buttonPer = new JButton();
        buttonRev = new JButton();
        buttonMul = new JButton();
        buttonSub = new JButton();
        buttonAdd = new JButton();
        buttonEqual = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setBackground(new Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new Color(204, 204, 204));

        labelDisplay.setBackground(new Color(204, 255, 255));
        labelDisplay.setFont(new Font("Tahoma", 0, 33)); // NOI18N
        labelDisplay.setHorizontalAlignment(SwingConstants.RIGHT);
        labelDisplay.setText("0");
        labelDisplay.setBorder(new SoftBevelBorder(BevelBorder.LOWERED));
        labelDisplay.setOpaque(true);

        labelClear.setText("All Clear");
        labelClear.addMouseListener(new MouseAdapter() {
            public void mouseReleased(MouseEvent evt) {
                labelClearMouseReleased(evt);
            }
        });

        jSeparator1.setBackground(new Color(204, 204, 204));
        jSeparator1.setForeground(new Color(0, 0, 0));

        jPanel2.setBackground(new Color(204, 204, 204));

        buttonMc.setBackground(new Color(255, 102, 0));
        buttonMc.setFont(new Font("Tahoma", 1, 12)); // NOI18N
        buttonMc.setText("MC");
        buttonMc.setBorder(new SoftBevelBorder(BevelBorder.RAISED));
        buttonMc.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                buttonMcActionPerformed(evt);
            }
        });

        button7.setFont(new Font("Tahoma", 1, 12)); // NOI18N
        button7.setText("7");
        button7.setBorder(new SoftBevelBorder(BevelBorder.RAISED));
        button7.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });

        button4.setFont(new Font("Tahoma", 1, 12)); // NOI18N
        button4.setText("4");
        button4.setBorder(new SoftBevelBorder(BevelBorder.RAISED));
        button4.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });

        button1.setFont(new Font("Tahoma", 1, 12)); // NOI18N
        button1.setText("1");
        button1.setBorder(new SoftBevelBorder(BevelBorder.RAISED));
        button1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button0.setFont(new Font("Tahoma", 1, 12)); // NOI18N
        button0.setText("0");
        button0.setBorder(new SoftBevelBorder(BevelBorder.RAISED));
        button0.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                button0ActionPerformed(evt);
            }
        });

        buttonMr.setBackground(new Color(255, 102, 0));
        buttonMr.setFont(new Font("Tahoma", 1, 12)); // NOI18N
        buttonMr.setText("MR");
        buttonMr.setBorder(new SoftBevelBorder(BevelBorder.RAISED));
        buttonMr.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                buttonMrActionPerformed(evt);
            }
        });

        button8.setFont(new Font("Tahoma", 1, 12)); // NOI18N
        button8.setText("8");
        button8.setBorder(new SoftBevelBorder(BevelBorder.RAISED));
        button8.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });

        button5.setFont(new Font("Tahoma", 1, 12)); // NOI18N
        button5.setText("5");
        button5.setBorder(new SoftBevelBorder(BevelBorder.RAISED));
        button5.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });

        button2.setFont(new Font("Tahoma", 1, 12)); // NOI18N
        button2.setText("2");
        button2.setBorder(new SoftBevelBorder(BevelBorder.RAISED));
        button2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        buttonDot.setFont(new Font("Tahoma", 1, 12)); // NOI18N
        buttonDot.setText(".");
        buttonDot.setBorder(new SoftBevelBorder(BevelBorder.RAISED));
        buttonDot.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                buttonDotActionPerformed(evt);
            }
        });

        buttonMp.setBackground(new Color(255, 102, 0));
        buttonMp.setFont(new Font("Tahoma", 1, 12)); // NOI18N
        buttonMp.setText("M+");
        buttonMp.setBorder(new SoftBevelBorder(BevelBorder.RAISED));
        buttonMp.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                buttonMpActionPerformed(evt);
            }
        });

        button9.setFont(new Font("Tahoma", 1, 12)); // NOI18N
        button9.setText("9");
        button9.setBorder(new SoftBevelBorder(BevelBorder.RAISED));
        button9.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });

        button6.setFont(new Font("Tahoma", 1, 12)); // NOI18N
        button6.setText("6");
        button6.setBorder(new SoftBevelBorder(BevelBorder.RAISED));
        button6.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });

        button3.setFont(new Font("Tahoma", 1, 12)); // NOI18N
        button3.setText("3");
        button3.setBorder(new SoftBevelBorder(BevelBorder.RAISED));
        button3.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        buttonOpposite.setBackground(new Color(102, 255, 102));
        buttonOpposite.setFont(new Font("Tahoma", 1, 10)); // NOI18N
        buttonOpposite.setText("+/_");
        buttonOpposite.setBorder(new SoftBevelBorder(BevelBorder.RAISED));
        buttonOpposite.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                buttonOppositeActionPerformed(evt);
            }
        });

        buttonMm.setBackground(new Color(255, 102, 0));
        buttonMm.setFont(new Font("Tahoma", 1, 12)); // NOI18N
        buttonMm.setText("M-");
        buttonMm.setBorder(new SoftBevelBorder(BevelBorder.RAISED));
        buttonMm.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                buttonMmActionPerformed(evt);
            }
        });

        buttonSq.setBackground(new Color(102, 255, 102));
        buttonSq.setFont(new Font("Tahoma", 1, 12)); // NOI18N
        buttonSq.setText("√");
        buttonSq.setBorder(new SoftBevelBorder(BevelBorder.RAISED));
        buttonSq.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                buttonSqActionPerformed(evt);
            }
        });

        buttonDiv.setBackground(new Color(102, 255, 102));
        buttonDiv.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        buttonDiv.setText("÷");
        buttonDiv.setBorder(new SoftBevelBorder(BevelBorder.RAISED));
        buttonDiv.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                buttonDivActionPerformed(evt);
            }
        });

        buttonPer.setBackground(new Color(102, 255, 102));
        buttonPer.setFont(new Font("Tahoma", 1, 12)); // NOI18N
        buttonPer.setText("%");
        buttonPer.setBorder(new SoftBevelBorder(BevelBorder.RAISED));
        buttonPer.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                buttonPerActionPerformed(evt);
            }
        });

        buttonRev.setBackground(new Color(102, 255, 102));
        buttonRev.setFont(new Font("Tahoma", 1, 10)); // NOI18N
        buttonRev.setText("1/x");
        buttonRev.setBorder(new SoftBevelBorder(BevelBorder.RAISED));
        buttonRev.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                buttonRevActionPerformed(evt);
            }
        });

        buttonMul.setBackground(new Color(102, 255, 102));
        buttonMul.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        buttonMul.setText("×");
        buttonMul.setBorder(new SoftBevelBorder(BevelBorder.RAISED));
        buttonMul.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                buttonMulActionPerformed(evt);
            }
        });

        buttonSub.setBackground(new Color(102, 255, 102));
        buttonSub.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        buttonSub.setText("_");
        buttonSub.setBorder(new SoftBevelBorder(BevelBorder.RAISED));
        buttonSub.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                buttonSubActionPerformed(evt);
            }
        });

        buttonAdd.setBackground(new Color(102, 255, 102));
        buttonAdd.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        buttonAdd.setText("+");
        buttonAdd.setBorder(new SoftBevelBorder(BevelBorder.RAISED));
        buttonAdd.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        buttonEqual.setBackground(new Color(102, 255, 102));
        buttonEqual.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        buttonEqual.setText("=");
        buttonEqual.setBorder(new SoftBevelBorder(BevelBorder.RAISED));
        buttonEqual.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                buttonEqualActionPerformed(evt);
            }
        });

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(buttonMc, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonMr, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonMp, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonMm, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSq, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(button0, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button1, GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(button2, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDot, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(button3, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSub, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(buttonOpposite, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonAdd, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonEqual, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(button4, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(button5, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(button6, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(buttonMul, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonRev, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(button7, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(button8, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(button9, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(buttonDiv, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(buttonPer, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(buttonMc, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonMr, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonMp, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonMm, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonSq, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(button7, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                            .addComponent(button8, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                            .addComponent(button9, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonDiv, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonPer, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(button4, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                            .addComponent(button6, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonRev, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonMul, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)))
                    .addComponent(button5, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addComponent(button1, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                                .addComponent(button2, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE))
                            .addComponent(buttonSub, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(buttonEqual, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(button3, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(button0, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDot, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonOpposite, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAdd, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)))
        );

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelClear)
                        .addGap(9, 9, 9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(labelDisplay, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(labelDisplay, GroupLayout.PREFERRED_SIZE, 62, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(labelClear)
                    .addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelClearMouseReleased(MouseEvent evt) {//GEN-FIRST:event_labelClearMouseReleased
        control.clearAll();
    }//GEN-LAST:event_labelClearMouseReleased

    private void button0ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_button0ActionPerformed
//        control.clickButton0();
        control.clickBt0();
    }//GEN-LAST:event_button0ActionPerformed

    private void buttonDotActionPerformed(ActionEvent evt) {//GEN-FIRST:event_buttonDotActionPerformed
//        control.clickDot();
        control.clickBtDot();
    }//GEN-LAST:event_buttonDotActionPerformed

    private void buttonOppositeActionPerformed(ActionEvent evt) {//GEN-FIRST:event_buttonOppositeActionPerformed
//        control.clickNegate();
        control.clickBtNegative();
    }//GEN-LAST:event_buttonOppositeActionPerformed

    private void buttonAddActionPerformed(ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
//        control.clickAdd();
        control.clickBtAdd();
    }//GEN-LAST:event_buttonAddActionPerformed

    private void buttonEqualActionPerformed(ActionEvent evt) {//GEN-FIRST:event_buttonEqualActionPerformed
        control.clickEqual();
    }//GEN-LAST:event_buttonEqualActionPerformed

    private void buttonSubActionPerformed(ActionEvent evt) {//GEN-FIRST:event_buttonSubActionPerformed
//        control.clickSub();
        control.clickBtSubtract();
    }//GEN-LAST:event_buttonSubActionPerformed

    private void button3ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
//        control.clickButton3();
        control.clickBt3();
    }//GEN-LAST:event_button3ActionPerformed

    private void button2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
//        control.clickButton2();
        control.clickBt2();
    }//GEN-LAST:event_button2ActionPerformed

    private void button1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
//        control.clickButton1();    }//GEN-LAST:event_button1ActionPerformed
        control.clickBt1();
    }

    private void button4ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
//        control.clickButton4();
        control.clickBt4();
    }//GEN-LAST:event_button4ActionPerformed

    private void button5ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
//        control.clickButton5();
        control.clickBt5();
    }//GEN-LAST:event_button5ActionPerformed

    private void button6ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
//        control.clickButton6();
        control.clickBt6();
    }//GEN-LAST:event_button6ActionPerformed

    private void buttonMulActionPerformed(ActionEvent evt) {//GEN-FIRST:event_buttonMulActionPerformed
//        control.clickMul();
        control.clickBtMultiple();
    }//GEN-LAST:event_buttonMulActionPerformed

    private void buttonRevActionPerformed(ActionEvent evt) {//GEN-FIRST:event_buttonRevActionPerformed
//        control.clickInverse();
        control.clickBtInverse();
    }//GEN-LAST:event_buttonRevActionPerformed

    private void buttonPerActionPerformed(ActionEvent evt) {//GEN-FIRST:event_buttonPerActionPerformed
//        control.clickPercent();
        control.clickBtPercent();
    }//GEN-LAST:event_buttonPerActionPerformed

    private void buttonSqActionPerformed(ActionEvent evt) {//GEN-FIRST:event_buttonSqActionPerformed
//        control.clickSqr();
        control.clickBtSqrt();
    }//GEN-LAST:event_buttonSqActionPerformed

    private void buttonDivActionPerformed(ActionEvent evt) {//GEN-FIRST:event_buttonDivActionPerformed
//        control.clickDiv();
        control.clickBtDivide();
    }//GEN-LAST:event_buttonDivActionPerformed

    private void button9ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
//        control.clickButton9();
        control.clickBt9();
    }//GEN-LAST:event_button9ActionPerformed

    private void button8ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
//        control.clickButton8();
        control.clickBt8();
    }//GEN-LAST:event_button8ActionPerformed

    private void button7ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
//        control.clickButton7();
        control.clickBt7();
    }//GEN-LAST:event_button7ActionPerformed

    private void buttonMcActionPerformed(ActionEvent evt) {//GEN-FIRST:event_buttonMcActionPerformed
        control.clearSecMemory();
    }//GEN-LAST:event_buttonMcActionPerformed

    private void buttonMrActionPerformed(ActionEvent evt) {//GEN-FIRST:event_buttonMrActionPerformed
        control.clickMR();
    }//GEN-LAST:event_buttonMrActionPerformed

    private void buttonMpActionPerformed(ActionEvent evt) {//GEN-FIRST:event_buttonMpActionPerformed
//        control.clickMp();
        control.clickMAdd();
    }//GEN-LAST:event_buttonMpActionPerformed

    private void buttonMmActionPerformed(ActionEvent evt) {//GEN-FIRST:event_buttonMmActionPerformed
//        control.clickMm();
        control.clickMSub();
    }//GEN-LAST:event_buttonMmActionPerformed

    
    
    public JButton getButton0() {
        return button0;
    }

    public JButton getButton2() {
        return button2;
    }

    public JButton getButton3() {
        return button3;
    }

    public JButton getButton4() {
        return button4;
    }

    public JButton getButton5() {
        return button5;
    }

    public JButton getButton6() {
        return button6;
    }

    public JButton getButton7() {
        return button7;
    }

    public JButton getButton8() {
        return button8;
    }

    public JButton getButton9() {
        return button9;
    }

    public JButton getButtonAdd() {
        return buttonAdd;
    }

    public JButton getButtonDiv() {
        return buttonDiv;
    }

    public JButton getButtonDot() {
        return buttonDot;
    }

    public JButton getButtonEqual() {
        return buttonEqual;
    }

    public JButton getButtonMc() {
        return buttonMc;
    }

    public JButton getButtonMm() {
        return buttonMm;
    }

    public JButton getButtonMp() {
        return buttonMp;
    }

    public JButton getButtonMr() {
        return buttonMr;
    }

    public JButton getButton1() {
        return button1;
    }

    public JButton getButtonMul() {
        return buttonMul;
    }

    public JButton getButtonOpposite() {
        return buttonOpposite;
    }

    public JButton getButtonPer() {
        return buttonPer;
    }

    public JButton getButtonRev() {
        return buttonRev;
    }

    public JButton getButtonSq() {
        return buttonSq;
    }

    public JButton getButtonSub() {
        return buttonSub;
    }

    public JLabel getLabelClear() {
        return labelClear;
    }
    
    public JLabel getLabelDisplay() {
        return labelDisplay;
    }
    
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        new CalculatorFrame().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton button0;
    private JButton button1;
    private JButton button2;
    private JButton button3;
    private JButton button4;
    private JButton button5;
    private JButton button6;
    private JButton button7;
    private JButton button8;
    private JButton button9;
    private JButton buttonAdd;
    private JButton buttonDiv;
    private JButton buttonDot;
    private JButton buttonEqual;
    private JButton buttonMc;
    private JButton buttonMm;
    private JButton buttonMp;
    private JButton buttonMr;
    private JButton buttonMul;
    private JButton buttonOpposite;
    private JButton buttonPer;
    private JButton buttonRev;
    private JButton buttonSq;
    private JButton buttonSub;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JSeparator jSeparator1;
    private JLabel labelClear;
    private JLabel labelDisplay;
    // End of variables declaration//GEN-END:variables
}
